name: Lint

on:
  pull_request:

permissions:
  contents: read

jobs:
  lint:
    if: github.actor != 'dependabot[bot]'
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version-file: ".python-version"

      - name: Run Ruff
        uses: astral-sh/ruff-action@v3
